### ISSUE TITLE
Failed to create CBR

### ISSUE THREAD

**Issue by kf0mlb** [shibi391/Codown#3]
I attempted the Star Wars Issue 45 (2015) download that you showed in the presentation gif.  It did download the pages, but failed to archive the files.

```
Scraping readcomiconline...
Scraped readcomiconline successfully
Downloading comic pages...
Download Complete
Converting images into cbr format...
Traceback (most recent call last):
  File "downloader.py", line 52, in <module>
    patoolib.create_archive(f"{path}\\" + f"#{issue_number}.cbr", images, verbosity=-1)
  File "C:\Users\firedrow\AppData\Local\Programs\Python\Python37-32\lib\site-packages\patoolib\__init__.py", line 716, in create_archive
    interactive=interactive, program=program)
  File "C:\Users\firedrow\AppData\Local\Programs\Python\Python37-32\lib\site-packages\patoolib\__init__.py", line 507, in _create_archive
    program = find_archive_program(format, 'create', program=program)
  File "C:\Users\firedrow\AppData\Local\Programs\Python\Python37-32\lib\site-packages\patoolib\__init__.py", line 336, in find_archive_program
    raise util.PatoolError("could not find an executable program to %s format %s; candidates are (%s)," % (command, format, ",".join(programs)))
patoolib.util.PatoolError: could not find an executable program to create format rar; candidates are (rar),
```

I use Bandizip or Peazip for all my archiving needs.  Using CBZ may be easier since Windows has zip built-in, then you just rename .zip to .cbz.  Or include the Win32 port of linux tools rar.

**Comment by jbclew** [comment]
> I attempted the Star Wars Issue 45 (2015) download that you showed in the presentation gif. It did download the pages, but failed to archive the files.
> 
> ```
> Scraping readcomiconline...
> Scraped readcomiconline successfully
> Downloading comic pages...
> Download Complete
> Converting images into cbr format...
> Traceback (most recent call last):
>   File "downloader.py", line 52, in <module>
>     patoolib.create_archive(f"{path}\\" + f"#{issue_number}.cbr", images, verbosity=-1)
>   File "C:\Users\firedrow\AppData\Local\Programs\Python\Python37-32\lib\site-packages\patoolib\__init__.py", line 716, in create_archive
>     interactive=interactive, program=program)
>   File "C:\Users\firedrow\AppData\Local\Programs\Python\Python37-32\lib\site-packages\patoolib\__init__.py", line 507, in _create_archive
>     program = find_archive_program(format, 'create', program=program)
>   File "C:\Users\firedrow\AppData\Local\Programs\Python\Python37-32\lib\site-packages\patoolib\__init__.py", line 336, in find_archive_program
>     raise util.PatoolError("could not find an executable program to %s format %s; candidates are (%s)," % (command, format, ",".join(programs)))
> patoolib.util.PatoolError: could not find an executable program to create format rar; candidates are (rar),
> ```
> 
> I use Bandizip or Peazip for all my archiving needs. Using CBZ may be easier since Windows has zip built-in, then you just rename .zip to .cbz. Or include the Win32 port of linux tools rar.

I had a similar problem  I was able to fix it by changing line 52 in downloader.py to this.

patoolib.create_archive(f"{path}\\" + f"#{issue_number}.zip", images, verbosity=-1)

Then add this line right below it.
os.rename(f"{path}\\" + f"#{issue_number}.zip", f"{path}\\" + f"#{issue_number}.cbr")

**Comment by iShibi** [comment]
@firedrow @jbclew thanks for your inputs. This program is a bit unstable as I have not worked on it since ages, this was just an experiment. I would advise you to use [read_comic_offline.](https://github.com/shibi391/read_comic_offline) It is a terminal-based program for downloading comics, It is more stable than this GUI version and gets updated more frequently.
